#! /bin/sh
# ----------------- COMMAND LINE VARIABLE ASSIGNMENT ----------------- #
createPath=$1
if [ -z "${createPath}" ]
then
  createPath=$PWD
  echo "No directory provided. Cloning repos here: ${createPath}"
fi
# -------------------------------------------------------------------- #
# --------------------- MAKE SCRIPTS EXECUTABLE ---------------------- #
executables=( 'uic_greetings_setup' 'uic_stats_setup' 'web_dashboard_setup' 'svc_stats_setup' )
executablePath='/usr/local/bin/'
for executable in "${executables[@]}"
do
  cp $executable $executablePath
  chmod a+x $executablePath$executable
done
# -------------------------------------------------------------------- #
# ------------------------ CLONE GIT REPOS --------------------------- #
cd "$createPath"

githubRepos=( 'horde-uic-greetings' 'horde-web-dashboard' 'horde-svc-stats' 'horde-uic-stats' )

for repo in "${githubRepos[@]}" 
do
  git clone git@github.com:acima-credit/$repo.git
done
# -------------------------------------------------------------------- #
# -----------------------------UIC STATS------------------------------ #
#TODO: REMOVE ALL CHRUBY RELATED COMMANDS!
osascript \
  -e 'tell application "Terminal"' \
  -e 'tell application "System Events" to keystroke "t" using command down' \
  -e "do script \"cd ${createPath}horde-uic-stats; chruby 2.4.2; uic_stats_setup\" in front window" \
  -e "end tell" > /dev/null
# -------------------------------------------------------------------- #
# -------------------------- UIC GREETINGS --------------------------- #
osascript \
  -e 'tell application "Terminal"' \
  -e 'tell application "System Events" to keystroke "t" using command down' \
  -e "do script \"cd ${createPath}horde-uic-greetings; chruby 2.4.2; uic_greetings_setup\" in front window" \
  -e "end tell" > /dev/null
# -------------------------------------------------------------------- #
# ----------------------------- SVC STATS ---------------------------- #
osascript \
  -e 'tell application "Terminal"' \
  -e 'tell application "System Events" to keystroke "t" using command down' \
  -e "do script \"cd ${createPath}horde-svc-stats; svc_stats_setup\" in front window" \
  -e "end tell" > /dev/null
# -------------------------------------------------------------------- #
# --------------------------- WEB DASHBOARD -------------------------- #
osascript \
  -e 'tell application "Terminal"' \
  -e 'tell application "System Events" to keystroke "t" using command down' \
  -e "do script \"cd ${createPath}horde-web-dashboard; chruby 2.4.2; web_dashboard_setup\" in front window" \
  -e "end tell" > /dev/null
# -------------------------------------------------------------------- #
# ------------------------- TEMP CLEAN UP ---------------------------- #
#for executable in "${executables[@]}"
#do
#  rm $executablePath$executable
#done
# -------------------------------------------------------------------- #
