#! /bin/bash
# ----------------- COMMAND LINE VARIABLE ASSIGNMENT ----------------- #
createPath=$1
if [ -z "${createPath}" ]
then
  createPath=$PWD
  echo "No directory provided. Cloning repos here: ${createPath}"
fi
# -------------------------------------------------------------------- #

# ------------------------ CLONE GIT REPOS --------------------------- #
cd "$createPath"

githubRepos=( 'horde-uic-greetings' 'horde-web-dashboard' 'horde-svc-stats' 'horde-uic-stats' )

for repo in "${githubRepos[@]}" 
do
  #git clone git@github.com:acima-credit/$repo.git
  echo $repo
done
# -------------------------------------------------------------------- #

# -----------------------------UIC STATS------------------------------ #
osascript \
  -e 'tell application "Terminal"' \
  -e 'tell application "System Events" to keystroke "t" using command down' \
  -e "do script \"cd ${createPath}/horde-uic-stats\" in front window" \
  -e "end tell" > /dev/null
# -------------------------------------------------------------------- #
